### ISSUE TITLE
Is it a real open source software? for academic use, I can not rebuild it using VS 2019

### ISSUE THREAD

**Issue by 040840308** [ComodoSecurity/openedr#12]
Hello, Everyone

     Does someone rebuild this "open source" EDR successfully? I tried, but failed. Under Visual Studio 2019, the compilation failed with errors: 1) madCHook.h, No Such File or Directory. 2) System Includes.h No such file or directory. 3) No libboost_date_time-vc142-mt-sgd-x64-1_70.lib。

    I'm not sure whether this project is indeed going to work for everyone. If not, I will try other open source projects for academic use. If yes, please give more instructions about how to compile and rebuild this project.

    Thanks

**Comment by ozercomodo** [comment]
we have 2 3rd part dependencies: please check licensing, they are free or charge but you need to get in touch with them to get the source code to build those libraries. 

Please also check the Readme under
openedr/edrav2/eprj/madchook/
openedr/edrav2/eprj/madchookdrv/
openedr/edrav2/eprj/nfsdk/

you should add those source code to build it from scratch. 
Alternatively you can just use prebuilt installer or use free version from here : https://enterprise.platform.comodo.com/signup

**Comment by keenjoy95** [comment]
Dependency list:

libboost_date_time-vc142-mt-sgd-x64-1_70.lib
libboost_regex-vc142-mt-sgd-x64-1_70.lib
libboost_thread-vc142-mt-sgd-x64-1_70.lib
libboost_chrono-vc142-mt-sgd-x64-1_70.lib
libboost_locale-vc142-mt-sgd-x64-1_70.lib
libboost_context-vc142-mt-sgd-x64-1_70.lib
libboost_coroutine-vc142-mt-sgd-x64-1_70.lib
jsoncpp_lib.lib
jsonrpccpp-common.lib
jsonrpccpp-client.lib
jsonrpccpp-server.lib
log4cplusSD.lib
libmicrohttpd_d.lib
libcurl-d.lib
tiny-aes.lib
madCHook.lib
nfapi.lib
ProtocolFilters.lib
network-uri.lib
aws-cpp-sdk-core.lib
aws-cpp-sdk-firehose.lib
libssl.lib
libcrypto.lib
gpr.lib
grpc.lib
grpc++.lib
address_sorting.lib
cares.lib
libprotobufd.lib
zlibd.lib
