### ISSUE TITLE
Output Events  not in CRLF format

### ISSUE THREAD

**Issue by michaelhidalgo** [ComodoSecurity/openedr#14]
Hey guys, I realized that the logs in the output folder C:\ProgramData\edrsvc\log\output_events, although they are a valid JSON, do not have a proper CRLF (carriage return line ending) (as you can see in line 57 below).

This is a bit problematic if you want to read the logs with Filebeat for instance. Is it possible to add a CRLF per line? Or even better that the JSON are not beautified (not pretty output)? That way we save time because there will be a JSON log per line with a proper carriage return.

![Screen Shot 2020-11-27 at 16 18 32](https://user-images.githubusercontent.com/1732035/100488337-375ce680-30d3-11eb-9ab3-009a67266633.png)

**Comment by pbasilcom** [comment]
Already fixed by https://github.com/ComodoSecurity/openedr/commit/6426e53f3e02eda319d896eaecbfc21d3fdc3e99
