### ISSUE TITLE
How to stop edrsvc service 

### ISSUE THREAD

**Issue by tamermh** [ComodoSecurity/openedr#15]
Hi,

when i try (as admin or system) to stop edrsvc using **sc stop edrsvc**, i am getting this 

**[SC] ControlService FAILED 1052:

The requested control is not valid for this service.**

Thanks for help

**Comment by pkorshak** [comment]
Use edrsvc.exe to stop service:
`%OPENEDR_INSTALLATION_PATH%\edrsvc.exe -stop`

**Comment by CN016** [comment]
![Image](https://github.com/user-attachments/assets/4f2a4744-55cb-4e5f-94ad-ac3ccfe8e1c3)
pleace see my images
